-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:fd5127dc2ec68f3dfe02a3a6eeac20ab$
-- 

local fileWidth = 512
local fileHeight = 512

local entityHeight = 112
local entityWidth = 128

local norm_asset_width = entityWidth/fileWidth
local norm_asset_height = entityHeight/fileHeight

local sprites_per_line = 4

local towerSize = 39

local names = {"yellow_tower.png", "red_tower.png", "green_tower.png", "blue_tower.png", "black_space.png", "brown_space.png"}

local images = {}

for i=1, #names, 1 do
    u0 = ((i-1)%sprites_per_line) * norm_asset_width -- X0
    v0 = math.floor((i-1)/sprites_per_line) * norm_asset_height -- Y0
    u1 = (i%sprites_per_line) * norm_asset_width -- X1
    v1 = (math.floor((i-1)/sprites_per_line) + 1) * norm_asset_height -- X2
    
    if i == sprites_per_line then
        u1 = 1
    end
        
    table.insert(images, {
        name = names[i],--"yellow_tower.png",
        spriteColorRect = {x = 0, y = 0, width = towerSize, height = towerSize }, -- This is the height and width of the object
        uvRect = { u0 = u0, v0 = v0, u1 = u1, v1 = v1},
        spriteSourceSize = { width = towerSize, height = towerSize },
        spriteTrimmed = true,
        textureRotated = false
    })
end

return {
	texture = 'tp_image.png',
    frames = images
	}
