-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:fd5127dc2ec68f3dfe02a3a6eeac20ab$
-- 

local fileWidth = 512
local fileHeight = 512

local entityHeight = 112
local entityWidth = 128

local norm_asset_width = entityWidth/fileWidth
local norm_asset_height = entityHeight/fileHeight

local towerSize = 39

return {
	texture = 'tp_image.png',
	frames = {
            {
                name = "yellow_tower.png",
                spriteColorRect = {x = 0, y = 0, width = towerSize, height = towerSize }, -- This is the height and width of the object
                uvRect = { u0 = 0, v0 = 0, u1 = norm_asset_width, v1 = norm_asset_height},
                spriteSourceSize = { width = towerSize, height = towerSize },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "red_tower.png",
                spriteColorRect = {x = 0, y = 0, width = towerSize, height = towerSize }, -- This is the height and width of the object
                uvRect = { u0 = 0, v0 = norm_asset_height, u1 = 1 * norm_asset_width, v1 = 2*norm_asset_height}, -- black space
                uvRect = { u0 = norm_asset_width, v0 = 0, u1 = 2 * norm_asset_width, v1 = 1 * norm_asset_height},
                spriteSourceSize = { width = towerSize, height = towerSize },
                spriteTrimmed = true,
                textureRotated = false
            },
            {
                name = "black_tower.png",
                spriteColorRect = {x = 0, y = 0, width = towerSize, height = towerSize }, -- This is the height and width of the object
                uvRect = { u0 = 0, v0 = norm_asset_height, u1 = 1 * norm_asset_width, v1 = 2*norm_asset_height}, -- black space
                spriteSourceSize = { width = towerSize, height = towerSize },
                spriteTrimmed = true,
                textureRotated = false
            },
            
        --[[
			{
				name = "checkbox_bg.png",
				spriteColorRect = { x = 4, y = 4, width = 34, height = 34 },
				uvRect = { u0 = 0.390625, v0 = 0.242188, u1 = 0.65625, v1 = 0.375 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "checkbox_mark.png",
				spriteColorRect = { x = 1, y = 2, width = 46, height = 34 },
				uvRect = { u0 = 0.015625, v0 = 0.242188, u1 = 0.375, v1 = 0.375 },
				spriteSourceSize = { width = 48, height = 40 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "gb-down.png",
				spriteColorRect = { x = 3, y = 4, width = 32, height = 32 },
				uvRect = { u0 = 0.671875, v0 = 0.375, u1 = 0.921875, v1 = 0.5 },
				spriteSourceSize = { width = 38, height = 38 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "gb-up.png",
				spriteColorRect = { x = 3, y = 4, width = 32, height = 32 },
				uvRect = { u0 = 0.671875, v0 = 0.242188, u1 = 0.921875, v1 = 0.367188 },
				spriteSourceSize = { width = 38, height = 38 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sz_down.png",
				spriteColorRect = { x = 1, y = 4, width = 60, height = 58 },
				uvRect = { u0 = 0.5, v0 = 0.0078125, u1 = 0.96875, v1 = 0.234375 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sz_up.png",
				spriteColorRect = { x = 1, y = 4, width = 60, height = 58 },
				uvRect = { u0 = 0.015625, v0 = 0.0078125, u1 = 0.484375, v1 = 0.234375 },
				spriteSourceSize = { width = 62, height = 62 },
				spriteTrimmed = true,
				textureRotated = false
			},--]]
		}
	}
